[project]
name = "localis"
version = "2.1.0"
description = "Fast, offline access to comprehensive data for countries, subdivisions, cities and macroregions. Built on ISO 3166, GeoNames and Unicode CLDR datasets (updated monthly) with support for exact lookups, filtering, and fuzzy search."
readme = "README.md"
authors = [
  {name = 'danimal', email= 'dan.stoffels@gmail.com'}
]
license = "MIT"
keywords = [
  "country", "subdivision", "city", "macroregion", "region", "state", "province",
  "iso", "3166", "iso-3166", "3166-1", "3166-2", "3166-3", "m49",
  "geonames", "cldr", "wikidata",
  "geography", "geodata", "gazetteer", "offline", "fuzzy-search",
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Scientific/Engineering :: GIS",
]
requires-python = ">=3.11"
dependencies = [
  "rapidfuzz>=3.13.0",
  "unidecode>=1.4.0",
]

[project.urls]
homepage = "https://pypi.org/project/localis/"
repository = "https://github.com/dstoffels/localis"
funding = "https://github.com/sponsors/dstoffels"

[project.scripts]
test = "pytest:console_main"
test-watch = "pytest_watch.command:main"
ingest = "ingest.__main__:main"
analysis = "tests.analysis.__main__:main"

[tool.poetry]
packages = [
  { include = "localis", from = "src" },
  { include = "ingest" }
]
exclude = ["ingest/**"]


[tool.poetry.group.dev.dependencies]
pytest = ">=8.4.1"
pytest-watch = ">=4.2.0"
pytest-cov = "^7.0.0"
pytest-xdist = "^3.8.0"
black = "^25.11.0"
ruff = "^0.14.6"
watchfiles = "^1.1.1"
mcp = "^2.2.0"
pyright = "^1.1.414"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"