[pytest]
addopts = -v --capture=tee-sys --cov=localis
norecursedirs = __pycache__/ .pytest_cache .venv
testpaths =
  tests

[pytest-watch]
ignore = 
  ./**/__pycache__ 
  ./**/.pytest_cache 
  ./**/.venv 
  ./**/logs
