name: Release

on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    if: >-
      github.repository == 'dstoffels/localis' &&
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'push'

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Get project version
        id: get_version
        run: echo "VERSION=v$(poetry version -s)" >> "$GITHUB_OUTPUT"

      - name: Check if already released
        id: check_versions
        run: |
          VERSION="${{ steps.get_version.outputs.VERSION }}"
          if git rev-parse -q --verify "refs/tags/$VERSION" >/dev/null; then
            echo "Tag $VERSION already exists. Nothing to release."
            echo "SHOULD_RELEASE=false" >> "$GITHUB_OUTPUT"
          else
            echo "New version $VERSION. Generating new release."
            echo "SHOULD_RELEASE=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Determine if pre-release (PEP 440).
        if: steps.check_versions.outputs.SHOULD_RELEASE == 'true'
        id: check_prerelease
        run: |
          RAW_VERSION=$(poetry version -s)

          if [[ "$RAW_VERSION" =~ (a|alpha|b|beta|rc|.dev)[0-9]*$ ]]; then
            echo "Incoming version is a pre-release."
            echo "IS_PRERELEASE=true" >> "$GITHUB_OUTPUT"
          else
            echo "IS_PRERELEASE=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Build
        if: steps.check_versions.outputs.SHOULD_RELEASE == 'true'
        run: poetry build

      - name: Generate new release
        if: steps.check_versions.outputs.SHOULD_RELEASE == 'true'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          name: ${{ steps.get_version.outputs.VERSION }}
          target_commitish: ${{ github.event.workflow_run.head_sha }}
          generate_release_notes: true
          draft: false
          prerelease: ${{ steps.check_prerelease.outputs.IS_PRERELEASE }}
          files: |
            dist/*.whl
            dist/*.tar.gz

      - name: Publish to PyPI
        if: steps.check_versions.outputs.SHOULD_RELEASE == 'true'
        uses: pypa/gh-action-pypi-publish@release/v1
